name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # updates every 6 hours

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
